# site settings
title: Web Personal Site
subtitle: by Renzo Tello
email: renzoadrian.tellojimenez@my.jcu.edu.au
description: Data Science Projects
baseurl: "/datascience" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 22 Angela St
city: Brisbane
state: QLD
zip_code: 4107
country: Australia
phone: (+61) 413 454 481

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
